# Generated by Django 3.1.2 on 2020-10-26 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datas',
            name='prediksi',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
