# Generated by Django 3.1.2 on 2020-11-22 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_datas_prediksi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datas',
            name='ipk_sm1',
        ),
        migrations.AddField(
            model_name='datas',
            name='ipk1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datas',
            name='ipk2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datas',
            name='ipk6',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datas',
            name='ipk_prodi',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datas',
            name='nama',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='datas',
            name='nim',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
