# Generated by Django 3.1.2 on 2020-11-22 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20201122_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='datas',
            name='ipk3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datas',
            name='ipk4',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datas',
            name='ipk5',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
