# Generated by Django 3.1.2 on 2021-02-15 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20201220_1603'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datas',
            old_name='hasil_bakat',
            new_name='hasil_baka_voli',
        ),
        migrations.RenameField(
            model_name='datas',
            old_name='kemampuan_fisik',
            new_name='kemampuan_fisi_tenis_meja',
        ),
        migrations.RenameField(
            model_name='datas',
            old_name='teknik_dasar',
            new_name='kemampuan_fisik_bulu_tangkis',
        ),
        migrations.AddField(
            model_name='datas',
            name='hasil_bakat_bulu_tangkis',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='datas',
            name='hasil_bakat_lari',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='datas',
            name='hasil_bakat_renang',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='datas',
            name='hasil_bakat_sepak_bola',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='datas',
            name='hasil_bakat_tenis_meja',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='datas',
            name='hasil_bakat_tolak_peluru',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='datas',
            name='kemampuan_fisik_lari',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='datas',
            name='kemampuan_fisik_renang',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='datas',
            name='kemampuan_fisik_sepak_bola',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='datas',
            name='kemampuan_fisik_tolak_peluru',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='datas',
            name='kemampuan_fisik_voli',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='datas',
            name='teknik_dasar_bulu_tangkis',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='datas',
            name='teknik_dasar_lari',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='datas',
            name='teknik_dasar_renang',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='datas',
            name='teknik_dasar_sepak_bola',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='datas',
            name='teknik_dasar_tenis_meja',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='datas',
            name='teknik_dasar_tolak_peluru',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='datas',
            name='teknik_dasar_voli',
            field=models.IntegerField(null=True),
        ),
    ]
