# Generated by Django 3.1.2 on 2021-02-15 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20210215_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datas',
            name='hasil_baka_voli',
        ),
        migrations.AddField(
            model_name='datas',
            name='hasil_bakat_voli',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
