# Generated by Django 3.1.2 on 2021-02-15 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20210215_1656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datas',
            name='kemampuan_fisi_tenis_meja',
        ),
        migrations.AddField(
            model_name='datas',
            name='kemampuan_fisik_tenis_meja',
            field=models.IntegerField(null=True),
        ),
    ]
