# Generated by Django 3.1.2 on 2021-06-16 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20210215_1711'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSiswa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_siswa', models.CharField(blank=True, max_length=100, null=True)),
                ('jenis_kelamin', models.CharField(blank=True, max_length=30, null=True)),
                ('tinggi_badan', models.IntegerField(null=True)),
                ('berat_badan', models.IntegerField(null=True)),
                ('kemampuan_fisik_lari', models.IntegerField(null=True)),
                ('teknik_dasar_lari', models.IntegerField(null=True)),
                ('kemampuan_fisik_voli', models.IntegerField(null=True)),
                ('teknik_dasar_voli', models.IntegerField(null=True)),
                ('kemampuan_fisik_renang', models.IntegerField(null=True)),
                ('teknik_dasar_renang', models.IntegerField(null=True)),
                ('kemampuan_fisik_bulu_tangkis', models.IntegerField(null=True)),
                ('teknik_dasar_bulu_tangkis', models.IntegerField(null=True)),
                ('kemampuan_fisik_sepak_bola', models.IntegerField(null=True)),
                ('teknik_dasar_sepak_bola', models.IntegerField(null=True)),
                ('kemampuan_fisik_tenis_meja', models.IntegerField(null=True)),
                ('teknik_dasar_tenis_meja', models.IntegerField(null=True)),
                ('kemampuan_fisik_tolak_peluru', models.IntegerField(null=True)),
                ('teknik_dasar_tolak_peluru', models.IntegerField(null=True)),
            ],
        ),
    ]
